export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as Experienced } from './Experienced'
export { default as Skills } from './Skills'
export { default as Portfolio } from './Portfolio'
